name: Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v5

      - name: Instalar Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Angular
        run: npm run build -- --configuration production

      - name: Subir archivos al servidor
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SOURCE: "dist/cms_ankama/browser/"
          TARGET: ${{ secrets.SERVER_PATH }}
          ARGS: "-rzv --delete --no-times --no-perms --omit-dir-times --exclude=data --exclude=update --exclude=tofurak.php --exclude=.htaccess"